### ISSUE TITLE
callr issue

### ISSUE THREAD

**Issue by dslramsey** [r-lib/callr#85] opened 2018-10-25 21:14 UTC
This was picked up while tracking down an issue on the rstan forum on a Win10 x64 system. R 3.5.1.

`system2("R", args = "CMD config CC")`
works but
`callr::rcmd_safe("config", "CC")`
errors with
`Error in eval(substitute(expr), data, enclos = parent.frame()) : is.character(repos) is not TRUE`
when called from `pkgbuild::has_build_tools` and @bgoodri in case it has anything to do with how rstan is calling it

**Comment by gaborcsardi** [comment] 2018-10-25 21:17
Duplicate of #82. Workaround is to make  your `options("repos")` a character vector.

**Closed by gaborcsardi** 2018-10-25 21:17 UTC
