### ISSUE TITLE
Stop with data transmission makes r return extremely laggy

### ISSUE THREAD

**Issue by renkun-ken** [r-lib/callr#195] opened 2021-04-12 04:41 UTC
If a slightly larger data is supplied to `callr::r()` or `callr::r_bg()` and the function stops, the function seems to always return very slowly. The following is a minimal example:

```r
n <- 1000
data1 <- data.frame(id = seq_len(n))
for (i in 1:50) {
  data1[[paste0("x", i)]] <- rnorm(n)
}

format(object.size(data1), units = "auto")
#> [1] "401.1 Kb"

system.time(r <- callr::r(function(data1) {
  message("done")
}, list(data1 = data1)))
#>    user  system elapsed 
#>   0.339   0.126   0.225

system.time(r <- callr::r(function(data1) {
  stop("error")
}, list(data1 = data1)))
#> Error: callr subprocess failed: error
#> Timing stopped at: 7.126 0.17 7.055
```

Created on 2021-04-12 by the reprex package (v2.0.0)

**Comment by gaborcsardi** [comment] 2021-04-12 07:28
Yes, this is a duplicate of #185 I believe.

**Closed** 2021-04-12 07:28 UTC

**Comment by renkun-ken** [comment] 2021-04-26 06:54
With the latest release, my case is still extremely slow. The following example will take forever:

```r
data1 <- data.table(id = 1:100000)
for (i in 1:50) {
  data1[, paste0("x", i) := rnorm(.N)]
}

system.time(r <- callr::r(function(data1) {
  stop("error")
}, list(data1 = data1)))
```

**Comment by gaborcsardi** [comment] 2021-04-26 07:36
Yeah, I know it is still an issue. The solution would be not to embed the passed objects into the call that callr evaluates in the subprocess. But that would mean creating some temporary variables, which callr is trying to avoid. It is also a bigger change, which might break things, unfortunately.
