### ISSUE TITLE
Error: cannot add binding of '.Traceback' to the base environment

### ISSUE THREAD

**Issue by wlandau** [r-lib/callr#197] opened 2021-04-15 15:36 UTC
On R-devel r80165 (2021-04-14) I get traceback errors while using `callr` from within `targets`. It appears to have something to do with [this line](https://github.com/r-lib/callr/blob/705c1bf61e2a646a8d68f8c7ced1f56e4c010a5e/R/script.R#L14), but I am having trouble reproducing the error outside `targets`. (Sorry about that). Here is what I can reproduce:

```r
> packageDescription("callr")$GithubSHA1
[1] "705c1bf61e2a646a8d68f8c7ced1f56e4c010a5e"
> library(targets)
> tar_script(tar_target(x, stop("msg")))
> tar_make()
● run target x
✖ error target x
● end pipeline
Error in assign(".Traceback", traceback(9), envir = baseenv()) : 
  cannot add binding of '.Traceback' to the base environment
> traceback()
No traceback available 
> sessionInfo()
R Under development (unstable) (2021-04-14 r80165)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS:   /home/<CENSORED>/custom_R/R-devel/lib/libRblas.so
LAPACK: /home/<CENSORED>/custom_R/R-devel/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] targets_0.3.1

loaded via a namespace (and not attached):
 [1] codetools_0.2-18  fansi_0.4.2       ps_1.6.0          withr_2.4.1      
 [5] crayon_1.4.1      utf8_1.2.1        digest_0.6.27     R6_2.5.0         
 [9] lifecycle_1.0.0   magrittr_2.0.1    pillar_1.6.0      rlang_0.4.10     
[13] cli_2.4.0         data.table_1.14.0 callr_3.6.0.9000  vctrs_0.3.7      
[17] ellipsis_0.3.1    tools_4.1.0       glue_1.4.2        purrr_0.3.4      
[21] igraph_1.2.6      compiler_4.1.0    processx_3.5.1    pkgconfig_2.0.3  
[25] tidyselect_1.1.0  tibble_3.1.0 
```

**Comment by gaborcsardi** [comment] 2021-04-15 15:43
This is a duplicate of #196.

**Closed by gaborcsardi** 2021-04-15 15:43 UTC
