### ISSUE TITLE
system2("Rscript", args ="-e 1") via r_session$new(): Fatal error: creating temporary file for '-e' failed

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/callr#236] opened 2022-10-07 19:16 UTC
# Issue

With:

```sh
rscript_tests <- function() {
  bin <- file.path(R.home("bin"), "Rscript")
  res <- list()
  res[[1]] <- system2(bin, args = list("--version"), stdout = TRUE)
  res[[2]] <- system2(bin, args = list("-e", "42"), stdout = TRUE)
  res
}
```

I get

```r
cat("rscript_tests() in a callr background session:\n")
rs <- callr::r_session$new()
res <- rs$run(rscript_tests)
str(res)
#> rscript_tests() in a callr background session:
#> List of 2
#>  $ : chr "Rscript (R) version 4.2.1 (2022-06-23)"
#>  $ : chr "Fatal error: creating temporary file for '-e' failed"
#>   ..- attr(*, "status")= int 2
```

It works in the main R session;

```r
cat("rscript_tests() in the main R session:\n")
res <- do.call(rscript_tests, args = list())
str(res)
#> rscript_tests() in the main R session:
#> List of 2
#>  $ : chr "Rscript (R) version 4.2.1 (2022-06-23)"
#>  $ : chr "[1] 42"
```

# Session info

```r
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /home/hb/shared/software/CBI/R-4.2.1-gcc9/lib/R/lib/libRblas.so
LAPACK: /home/hb/shared/software/CBI/R-4.2.1-gcc9/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] processx_3.7.0 compiler_4.2.1 callr_3.7.2    ps_1.7.1   
```

# Related

1. StackOverflow '[Why are the workers failing to connect when calling `makePSOCKcluster` from an external `R` process?](https://stackoverflow.com/questions/73962109)' on 2022-10-05.  The **parallel** package launches PSOCK workers using `Rscript -e ...`.
2. Probably also the reason for Issue #225 (parallelization via the futureverse not working)

/cc @wlandau

**Comment by gaborcsardi** [comment] 2022-10-08 13:18
This is because callr marks all file descriptors as close-on-exec and `system2()` assumes that stdin (etc.) will be inherited in the child process, and it won't, and the R subprocess will start up without stdin, and it cannot handle that:

```r
❯ echo 'processx::conn_disable_inheritance(); system2("Rscript", c("-e", "42"), stdout = TRUE)'  | R --vanilla -s
NULL
[1] "Fatal error: creating temporary file for '-e' failed"
attr(,"status")
[1] 2
```

A workaround is to set `stdin = "/dev/null"`, at least on Unix:

```r
❯ echo 'processx::conn_disable_inheritance(); system2("Rscript", c("-e", "42"), stdin = "/dev/null", stdout = TRUE)'  | R --vanilla -s
NULL
[1] "[1] 42"
```

Or use processx or callr:

```r
❯ echo 'processx::conn_disable_inheritance(); processx::run("Rscript", c("-e", "42"))'  | R --vanilla -s
NULL
$status
[1] 0

$stdout
[1] "[1] 42\n"

$stderr
[1] ""

$timeout
[1] FALSE
```

I guess these do not work for you because you are not the one calling `system()`. callr could avoid marking the standard streams, and then this would not fail. The potential complications are mild on Unix. Possibly also mild on Windows, where handles are not inherited by default, but I am not sure.

**Closed** 2022-10-08 17:02 UTC

**Comment by HenrikBengtsson** [comment] 2022-10-08 18:01
> This is because callr marks all file descriptors as close-on-exec 

I see.  I just tried in Rterm.exe on MS Windows 10, and there the original problem does not show, i.e. it works also with the default `stdin = ""`.

I also verified that your workaround using `stdin = nullfile()` works on Linux and MS Windows - don't know about macOS.


> system2() assumes that stdin (etc.) will be inherited in the child process, and it won't, and the R subprocess will start up without stdin

Can it be argued that this is something R/Rscript should handle, e.g. what was your reason? (sorry, this is beyond my thought bubble). That is, can one make a feature request/bug report for this to be fixed?

I see you've introduced `PROCESSX_CLOEXEC_STDIO` default to not do this in the devel version (https://github.com/r-lib/processx/commit/1082c9db2345b8dfa5c45eb88711a42a0b681ae7). 

Thanks

**Comment by mihaiconstantin** [comment] 2022-10-08 21:19
I can confirm that the changes in https://github.com/r-lib/processx/commit/1082c9db2345b8dfa5c45eb88711a42a0b681ae7 solved my question *[Why are the workers failing to connect when calling makePSOCKcluster from an external R process?](https://stackoverflow.com/questions/73962109)* on StackOverflow.

**Comment by gaborcsardi** [comment] 2022-10-09 07:59
> Can it be argued that this is something R/Rscript should handle, e.g. what was your reason? 

My reason for disabling inheritance of handles? It is the right thing to do:
- https://danwalsh.livejournal.com/53603.html
- https://wiki.sei.cmu.edu/confluence/display/c/FIO22-C.+Close+files+before+spawning+processes
- etc.

I think ideally `system()` would handle this situation and `dup*()` the file descriptors that the subprocess is supposed to inherit. Instead of just assuming that they will be inherited. E.g. processx does that.

Anyway, we can try not marking the standard streams, hopefully that will not cause too much trouble.

**Comment by HenrikBengtsson** [comment] 2022-10-09 17:40
Thank you.  Here's a way to reproduce the issue of R not being able to run with stdin being closes using vanilla Bash;

```sh
## 0<&- closes the standard input
$ Rscript -e 42 0<&-
Fatal error: creating temporary file for '-e' failed
```
